### ISSUE TITLE
Issues submitted via Google Form, how to get responses back to the submitter

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-qa-manage#1]
Copying this management issue from https://github.com/tdwg/dwc-qa/issues/20.

kevinlove commented 3 days ago
Seems like we have discussions forming already here in the issue queue, but we need to make sure the original submitter is able to participate. Do we need to add a mechanism for this? How should this work?
 @pzermoglio
     Collaborator
 pzermoglio commented 3 days ago • edited
Easiest would be for submitter to have a github account and watch...? But
difficult to convince many of the advantages of that...​ Should this be a
strong recommendation for webinar attendees? Just thoughts
 @kevinlove
     
kevinlove commented 3 days ago
@pzermoglio That seems like a pretty high bar to set. At best, we could ask if the user would like to associate a github username with the submission and set to watch if provided.

We should definitely send the user an email with a link to the issue and let them decide their level of interaction after that.
 @debpaul
     Member
debpaul commented 3 days ago
+1 @kevinlove with much encouragement to get github account (a friendly link).
 @tucotuco
     Member
 tucotuco commented 3 days ago
I think real participation and all its benefits are best realized by using
a GitHub account. Perhaps we can adapt this and reference it in the README.md

http://vertnet.org/resources/issuetrackingguide.html

and/or include it in a video orientation to the repository, also linked in
the README.md.

**Comment by tucotuco** [comment]
Summary, 

encourage users to create GitHub logins
create introductory material (in README.md and linked video) for how to do that
create introductory material (in README.md and linked video) for how to navigate the dwc-qa repository

**Comment by debpaul** [comment]
@tucotuco perhaps we add a field that lets those with github accounts provide their github username if they have one already?

**Comment by debpaul** [comment]
@iDigBioBot can we automate assignment of label:  "form submission"

**Comment by tucotuco** [comment]
Like both ideas - adding GitHub username to form and auto-generating label "form submission". Followed up with @kevinlove about these via email.

**Comment by tucotuco** [comment]
Done.
