### ISSUE TITLE
Prepare DwC Hour #10 (Nov) - Audubon Core/DwC extension implementation

### ISSUE THREAD

**Issue by garymotz** [VertNet/dwc-qa-manage#11]
Community best practices are in (early?) development and general adoption of DwC extensions (Audubon Core, in particular) is unclear to many users of DwC

Topics for this new webinar might include:

- How to link DwC occurrence records with media records using Audubon Core
- Integration of digitized collection objects for global discoverability and accessibility
- Appropriate metadata for 3D object description in Audubon Core

@tucotuco has indicated willingness to cover the first part of the webinar (mini-series) focused on DwC extensions and sharing media data for specimens
@garymotz has indicated willingness to cover the second part of the webinar (mini-series) focused on digitized 3D object management and developing community best practices on sharing 3D media

Given that this is a developing conversation with @danstoner and @hollyel I think it would be best if we aimed this webinar (mini-series) for August. That way we can meet and strategize at SPNHC.

**Comment by garymotz** [comment]
@pzermoglio or @tucotuco I'm unable to add labels or assign this issue to John and myself, would one of you please do this (or allow me to do it) for this issue? Thanks!

**Comment by tucotuco** [comment]
@garymotz You have been added to this repository as a collaborator, but the repository is destined to by subsumed in https://github.com/tdwg/dwc.

**Comment by debpaul** [comment]
@garymotz  I'm going to ping lots of folks today (in efforts to schedule Aug-Sept-Oct-Nov-Dec. While we hope (imagine) this scenario currently: August-Aggregators, Sept-the TDWG-GBIF DQ group, Oct-Kurator, ... availability will be an issue. So, options are nice. I see you claimed "DwC 12" so I'm guessing that August is not really an option you want to consider?

**Comment by garymotz** [comment]
@debpaul I'd assumed that we'd stick to our schedule of one per month and that November would likely be number 12. It is an arbitrary number, feel free to disregard! I'll do the webinar in November.

**Comment by garymotz** [comment]
@debpaul True, August is not an option that I'd like to consider. I think we've got a lot of work to do in order to get ready for this presentation...including the fact that I'm hoping to be defending my dissertation in August or very shortly thereafter. August is not an option for me.

**Comment by garymotz** [comment]
We've still got to keep things moving for this webinar. To do items include:

- [x] Schedule sound/screen check
- [x] Request survey content from presenters
- [x] Send presenters feedback request to Shari and get survey link from Shari at iDigBio
- [x] Generate tinyURL for survey
- [x] Written [intro](https://github.com/VertNet/dwc-qa-manage/wiki/Webinar-Preparation-Checklist#example-webinar-introduction-script) to webinar
- [x] Prepare AdobeConnect environment
- [x] Send emails advertising DwC Hour one week prior
- [x] Send emails advertising DwC Hour one day prior

**Comment by debpaul** [comment]
Hi @garymotz  we still need to Schedule exact date / time too?

Please have this to me before Oct 1st if possible - so that I can get it into the October iDigBio Newsletter.

**Comment by debpaul** [comment]
@garymotz I added calendar announcement at iDigBio and updated the tdwg/dwc-qa page with this title - abstract - and date. And scheduled sound check too.

**Comment by debpaul** [comment]
@garymotz :-) please send @hollyel the intro notes - thanks! She'll also need the titles for both you and Doug, to introduce you both.

**Comment by debpaul** [comment]
@garymotz @hollyel I've tentatively set up the adobe connect environment for next week's dwchour. You'll need to have a look at some point to make sure it's what you want.

NOTE: folks using the adobe connect environment don't always understand that they've co-opted someone else's pod. That's why sometimes when we've set it up, we go back to find it changed. IF you make a change in our POD Layouts, you can visit other layouts and see that our pods are in their layouts.

This is not a simple thing to teach people so we'll just have to recheck the day before (at Sound Check) and the day of...

**Comment by debpaul** [comment]
Hi again @hollyel  - the script for the intro (it's a sample - you'll need to edit) can be found [here](https://github.com/VertNet/dwc-qa-manage/wiki/Webinar-Preparation-Checklist#example-webinar-introduction-script)

**Comment by debpaul** [comment]
Short post webinar survey URL created: http://bit.ly/dwchour3D

**Comment by debpaul** [comment]
This webinar is done. But I leave it up to @garymotz and Doug Boyer to get together with @baskaufs, Bob Morris and others regarding working on the Audubon Core standard proposed additions needed for sharing 3D data. @garymotz at some point (after TDWG 2018 perhaps) it would be great to get an update.

**Comment by debpaul** [comment]
Closing this ticket.
