### ISSUE TITLE
DwC Hours August - December 2017 and into 2018

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#13]
Sending emails today to check availability & willingness to put together the following proposed webinars

- Aggregators (August 2017)
- TDWG-GBIF DQ (Sept 2017)
- Kurator (Oct 2017)
- Audubon Media Extension (Nov 2017) - we have a commitment from @garymotz - need date, abstract, etc.
- DwC 2017 Wrap-up (Dec 2017) - cover what's done, still to be covered, "the year in review"
- combining paleo+neontological data - invite Talia Karim - DwC Hour 2018
-dwc capturing Stratigraphy, paleobiology, isotope data sharing, zooarchaeological data (JW, et al - Rob Guralnick, Laura Brenskelle, Kitty Emory (archaeology), Michelle LeFevbre (post doc of Kitty) - Send Note to invite - DwC Hour 2018
- dwc geography including waterBody (drainage, marine division, pelagic, ...) JW 2018 (paper!) -DwC Hour 2018

**Comment by debpaul** [comment]
RESPONSE from TDWG-GBIF DQIG. They plan to discuss details for this at their upcoming May 2017 meeting in Canberra. Lee Belbin and Arthur Chapman have said yes. Currently, the times and dates are set for: 7 AM Wed Sept 6th (Tasmania time), 5 PM Tuesday Sept 5th (USA EDT), 6 PM Tuesday Sept 5th (Buenos Aires), Tues Sept 5th 21:00 UTC. NOTE the challenge to advertising across the international dateline. This will be DwC Hour number 8.

**Comment by debpaul** [comment]
Talia Karim has said yes - and suggests the following scenario. Her timeline is "fall" and we're deciding what that means exactly. She would present with co-author Virginia Scott, ENT collections mgr at CUMNH as they discuss the challenges of merging / sharing paleontological and neontological data together -  using the ENT and Paleo experience at CU as an example - and underlying this is the use of Specify as their common database.

ABSTRACT idea: a joint presentation talking about the difference between neontologic and paleo data and use insects/fossil insects as a case study.  We could describe which fields are shared, which are unique to our datasets, and then also highlight that even for shared fields, the data do not always mean the same thing. We have discovered this while mapping the Ento data to Darwin Core in the IPT.

**Comment by debpaul** [comment]
Email invite sent to aggregators - waiting now on RSVPs from them.

**Comment by debpaul** [comment]
Aggregator DwC Hour: GBIF prefers the 2nd week of August.

**Comment by debpaul** [comment]
Aggregator DwC Hour for GBIF and iDigBio set for August 15th. Added to Webinar Calendar and to iDigBio Calendar.

**Comment by debpaul** [comment]
Combining Neo+Paleo will be in September 2017.

**Comment by garymotz** [comment]
@debpaul We've now got Neo+Paleo scheduled in September with TDWG-GBIF DQIG already having selected a September date. Do we need to resolve the conflict or have two webinars in September?

We may need to clarify on https://github.com/tdwg/dwc-qa/wiki/Webinars.

**Comment by debpaul** [comment]
2 in September 🤗

Sent from shoe (iPhone)

On Jun 9, 2017, at 9:41 PM, garymotz <notifications@github.com<mailto:notifications@github.com>> wrote:


@debpaul<https://github.com/debpaul> We've now got Neo+Paleo scheduled in September with TDWG-GBIF DQIG already having selected a September date. Do we need to resolve the conflict or have two webinars in September?

**Comment by tucotuco** [comment]
VertNet available after 14 August and needs only about 20 minutes.

**Comment by debpaul** [comment]
@tucotuco could you please ping Canadensys to see if they'd like to present with you - and what date works for them? (if you have time).

**Comment by debpaul** [comment]
all issues here either done, or new separate tickets created. closing this ticket now.
See #11, #19, #20, #21
