### ISSUE TITLE
Next DMIG meeting - Ticket Review

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#14]
Next DMIG meeting on DwC Hour - Formal review of all the open issues in the dwc-qa/issues pile.

**Comment by garymotz** [comment]
@debpaul ...so, now we mean the _next_ DMIG meeting. And would you mean a DMIG meeting dedicated to GitHub issues organization as opposed to the DMIG meetings that occur on the Friday immediately following a webinar?

**Comment by ekrimmel** [comment]
scheduled for Thursday, Aug 31 at 11am EST

**Comment by debpaul** [comment]
This in done.
