### ISSUE TITLE
Date and Prepare Kurator DwC Hour #9 (Oct 2017)

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#18]
For @tucotuco - prepare the bits needed for a DwC Hour on Kurator for October 2017.
Date, time, abstract, links, presenters, moderators, etc.
IF provided before Sept 10th, this announcement would make the September iDigBio Newsletter.

**Comment by ekrimmel** [comment]
*discussion from [DwC Hour #7a: The Aggregator's Viewpoint - (More Than Vert)Net](https://github.com/tdwg/dwc-qa/wiki/Webinars#chapter7a)...*

**Deb Paul:** About Kurator: http://kurator.acis.ufl.edu/kurator-web/about. Kurator provides scientific workflow tools for data quality improvement of natural history collections and other biodiversity data. Kurator Web is a set of a user friendly web interface to configure and launch curation workflows while maintaining provenance. Kurator-Akka and the Kurator YesWorkflow data curation software and code are available on GitHub. For more information about Kurator, please visit our wiki. http://wiki.datakurator.org/wiki/

**Deb Paul:** What data formats (csv? .ods? .xls? xml? dwc-Archive?) can a person use with Kurator?

**John Wieczorek (speaking):** you can use any dialect of text, or a DWC-A data format

**Joanna (iDigBio):** @johnw what is the delivery date for first version of new Kurator?

**John Wieczorek (speaking):** Kurator is already available and functional, but will be gaining major functionality over the next year or so, and onward.

**Comment by ekrimmel** [comment]
*more discussion from [DwC Hour #7a: The Aggregator's Viewpoint - (More Than Vert)Net](https://github.com/tdwg/dwc-qa/wiki/Webinars#chapter7a)...*

**Gary Motz (Indiana Univ):** Can collection managers use the VertNet toolkit themselves to clean and high-grade collection data, especially before it goes back to the collection management software or DwC-A? Or should we just add to your growing waitlist?  ;)

**David Bloom:** Not yet, Gary, but that is part of the purpose of Kurator.

**Brad Millen, ROM, Toronto, Canada:** Waiting for Kurator to do just that!

**David Bloom:** In the meantime, feel free to contact me about getting the job done until you can do it yourself.

**John Wieczorek (speaking):** Some discussion of handholding new users trying to learn the migrator toolkit. Some of this documentation will happen during an upcoming workshop in Colombia. Within a year or so the migrator toolkit should be totally phased out by Kurator. Kurator already has a web interface, but has nowhere near the capabilities of the migrator toolkit.

**Comment by tucotuco** [comment]
Sent the following in email. Realize now I coulda/shoulda just done it here from the GitHub issue.

Title: Kurator Web: for Cleaner Biodiversity Data
When: Tuesday Oct 24 @ 11 AM EST, 12 PM ART, 3 PM UTC, 5 PM CEST
Where: http://idigbio.adobeconnect.com/room
Presenter: John Wieczorek Museum of Comparative Zoology, Harvard University; VertNet

Abstract:
When we think about biodiversity data and its use, we often immediately wonder about the data quality and how to improve it. The Kurator project is one of the initiatives addressing this issue, and aims at building data quality control and enhancement tools that can be readily used by people with different technical skill levels. One such tool is the Kurator Web application. This tool allows users to execute web-based data quality improvement workflows on biodiversity data, especially on data shared using Darwin Core terms, without the need for programming expertise. In this webinar we will demonstrate the use of Kurator Web to run pre-existing data quality workflows, some of which include: aligning datasets with Darwin Core terms, comparing unique values in datasets with controlled vocabularies, and providing suggestions for improvements for existing data. Finally, we will provide some context on how these tools can integrate with broader workflows and some perspective on the future of biodiversity data quality.

Links to relevant pre-reading materials for best experience:
Kurator Web http://kurator.acis.ufl.edu/kurator-web/
Kurator Web code https://github.com/kurator-org/kurator-web
Kurator Workflows https://github.com/kurator-org/kurator-validation/wiki

**Comment by tucotuco** [comment]
@debpaul Ready for the September newsletter.

**Comment by debpaul** [comment]
Nice! I'll get this published and see it makes the newsletter. Looking forward to this update.


Sent from my iPhone

On Sep 6, 2017, at 8:22 PM, John Wieczorek <notifications@github.com<mailto:notifications@github.com>> wrote:


@debpaul<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_debpaul&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=4u_nQHn8yqpaucZax8gJwaOUaTsq4WyEtxOlZ-oOh4U&s=I3PI5ewf0xBLnfC7z0PVexUu9GfeC2FZlWSOBfKMg30&e=> Ready for the September newsletter.

**Comment by debpaul** [comment]
Calendar announcement entered. See https://www.idigbio.org/content/darwin-core-hour-kurator-web-cleaner-biodiversity-data

Please note if you have a graphic (a logo for Kurator?) we could feature on the carousel front page of iDigBio.

**Comment by tucotuco** [comment]
If you want a logo, you could use the one found on

http://wiki.datakurator.org/wiki/Kurator-Web_User_Documentation

**Comment by debpaul** [comment]
Thanks @tucotuco only it's embedded, I cannot save it as a graphic and screen capture is too low resolution to work...

**Comment by debpaul** [comment]
Webinar done. Over 65 people showed up 👍 and there will be some followups for this one based on notes.
