### ISSUE TITLE
Date, Assign, Prep, December DwC 2017 Wrap-up #11

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#19]
Plan December DwC 2017 cover what's done, still to be covered, "the year in review." Include feedback from TDWG 2017 meeting.

**Comment by debpaul** [comment]
Some to-do's
- [x] Schedule sound/screen check
- [x] Request survey content from presenters
- [x] Send presenters feedback request to Shari and get survey link from Shari at iDigBio,
  in progress
- [x] Generate tinyURL for survey
- [x] Written [intro](https://github.com/VertNet/dwc-qa-manage/wiki/Webinar-Preparation-Checklist#example-webinar-introduction-script) to webinar
- [x] Prepare AdobeConnect environment
- [x] Send emails advertising DwC Hour one week prior
- [x] Send emails advertising DwC Hour one day prior

**Comment by debpaul** [comment]
- [x] create mp4 from Adobe Connect Recording (@ekrimmel  can you do this?)
- [x] link adobe connect recording on Webinars page http://idigbio.adobeconnect.com/pu48ho08pl43/
- [x] link mp4 recording to Webinars page

**Comment by ekrimmel** [comment]
Yep!

**Comment by ekrimmel** [comment]
[Link to webinar recording](https://www.dropbox.com/s/301kbae0pn87t5i/DwC%20Hour%20-%20Community%20Planning%20for%202018_96_0.mp4?dl=0). 

@kevinlove, for Vimeo when you have a chance. Thanks!

**Comment by kevinlove** [comment]
Added to Vimeo:
https://vimeo.com/245929146

@ekrimmel Can you use one of the default resolution when using the "Make Offline" feature? 3840 × 1448 is a non-standard resolution and creates scaling issues

**Comment by debpaul** [comment]
Thanks @ekrimmel for rendering the video! @garymotz and I don't seem to be able to do it anymore :-( 
Thanks @kevinlove for adding to vimeo - and guidance on the resolution issue. Closing this ticket.

**Comment by ekrimmel** [comment]
Sure thing @kevinlove! 3840 × 1448 *is* the default when I use the AC add-in, but I'm happy to change it to something better. What's better?
