### ISSUE TITLE
people interested in ongoing dwc:preparations discussion

### ISSUE THREAD

**Issue by ekrimmel** [VertNet/dwc-qa-manage#23]
At the conclusion of [DwC Hour #4: Evolution of Darwin Core Terms and Extensions](https://github.com/tdwg/dwc-qa/wiki/Webinars#chapter4) (see dwc-qa-manage issue #10), the following people expressed a direct interest in being part of the on-going **dwc:preparations** discussion:

- Amanda Millhouse, *paleo* (millhousea@si.edu)
- Carlos Martínez, *entomology*
- Greifswald University (biotemail@gmail.com)
- Beth Wommack, *vert paleo* (ewommack@uwyo.edu)
- Jess Miller-Camp, *UCR Earth Sciences* ( jessmc@ucr.edu): "If safety issues are something worth putting in preparation DWC, I'm happy to participate in that discussion."
- Gary Motz, *representing zooarchaeology, paleontology, and botany...from a collection manager, biodiversity informatics manager, and paleo-researcher perspective* (garymotz@indiana.edu)
- John Wieczorek, *DwC, zooarchaeology* (gtuco.btuco@gmail.com)
- Andy Bentley, *fish* (abentley@ku.edu)
- Randy Singer, *fish* (rsinger@flmnh.ufl.edu)
- Deborah Paul, *botany* (dpaul@fsu.edu)

*Disciplines missing: herps, mammals, birds, botany*

**Comment by tucotuco** [comment]
I would add Laura Brenskelle (lbrensk@gmail.com) from UF to the list for
zooarchaeology.

**Comment by tucotuco** [comment]
We should document this somewhere and close the Issue. Issues are targeted to be action items that can be closed. Otherwise we will keep looking at it for what needs to be done, and there is nothing to do on an list like this. Make sense?

**Comment by ekrimmel** [comment]
Agreed. I would see the action item here as some sort of working/interest group (that I think probably, to some extent, already exists). I would also see such a working group as beyond the direct scope of the DwC Hour group, and so IMO we could just pass this list of names on to the right person/people and close the issue (i.e. do we really need to document these on dwc-qa?) . My goal in including it here at all is to document our DwC Hour notes in a findable way, rather than to have them be lost in the future of Google Docs/Webinar Recordings of the Past. Whoever wants to work on this issue had 10 folks eagerly volunteer their names, so that's worth something to someone...

**Comment by garymotz** [comment]
FWIW, this group is already active and correspondence among the group listed here is already underway.
