### ISSUE TITLE
After webinars - editing steps about recordings / surveys / talks

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#27]
Hello all,
Adding to the Webinar Preparation Checklist https://github.com/VertNet/dwc-qa-manage/wiki/Webinar-Preparation-Checklist

1. Section labeled "after the webinar"
2. add step that mentions recordings / rendering the mp4 versions
3. add a step that includes putting the link for the talk (preferably a copy - to avoid deletion) in the folder: DarwinCoreHour-SharedFolder: https://drive.google.com/drive/folders/0B0Rlroh4mbthdnNqbjB6OXlhcE0
4. add a step to show where to put the post-webinar survey feedback. Shari Ellis says it's okay to make these public as they have been made anonymous.
5. add step that is linking the @iDigBio calendar Announcement to the Webinars Wiki: https://github.com/tdwg/dwc-qa/wiki/Webinars

**Comment by debpaul** [comment]
All above edits made but one. That is, where to put the survey feedback? Once that is decided and documented in the Webinar Preparation Checklist, we can close this issue.

**Comment by ekrimmel** [comment]
create a folder in this repository for survey feedback? that way we could link the issue related to the webinar to the file containing feedback...

**Comment by debpaul** [comment]
hm. For some reason, @tucotuco did not want to do that with presentations. So not sure about doing it with feedback documents. It's not the best place for documents.

**Comment by ekrimmel** [comment]
that's fair--pretty sure GitHub can't display Word docs (which is how Shari collates survey results?). Google Drive has equally unlikeable features IMO, in that files are easy to accidentally delete, and easy to lose track of in a wasteland of shared Google folders.

**Comment by debpaul** [comment]
yes @ekrimmel you've captured exactly why I'm also not the biggest fan of google drive. I've lost entire sets of documents because others have deleted.

**Comment by garymotz** [comment]
I could upload them to my institutional repository and assign them a DOI. The only issue from there might then be authorship and citation concerns. Thoughts?

**Comment by debpaul** [comment]
What about making each one a pdf (also not my favorite format - erg) but then we could have a folder here of pdfs? I believe GitHub can only display txt (csv) - and also uploaded images of course.

**Comment by tucotuco** [comment]
I like the idea of including the survey results in separate surveys folder.

**Comment by debpaul** [comment]
@tucotuco in what format (.doc .pdf)? and where?

**Comment by tucotuco** [comment]
PDFs? In a folder for surveys. But, on https://github.com/VertNet/dwc-qa-manage or on https://github.com/tdwg/dwc-qa?

**Comment by debpaul** [comment]
@tucotuco @ekrimmel perhaps we put the feedback in a folder on VertNet/dwc-qa-manage, but then put a link on /tdwg/dwc-qa to the folder?

**Comment by debpaul** [comment]
@tucotuco @ekrimmel @garymotz @pzermoglio @dagendresen @hollyel I've added a folder, see https://github.com/VertNet/dwc-qa-manage/tree/master/webinar-surveys with all the post-webinar surveys. They are in .docx format. Do we need PDF? I also added a post-webinar-survey.md file to explain the folder contents.

**Comment by tucotuco** [comment]
Excellent. Hmmm. I suspect only one or the other format is sufficient. PDF might be more readily viewable in general and a better choice. Is it worth the effort though?

**Comment by debpaul** [comment]
fairly easy to generate pdfs - just wanted to get the originals in there


On 2017-12-05 11:48 AM, John Wieczorek wrote:
>
> Excellent. Hmmm. I suspect only one or the other format is sufficient. 
> PDF might be more readily viewable in general and a better choice. Is 
> it worth the effort though?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_VertNet_dwc-2Dqa-2Dmanage_issues_27-23issuecomment-2D349365593&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=86MtOWMYAEhZKDqpAVArVopzV2PLs6QRwZl5F620Ge0&s=5xXWGgcMB_7TkfNgyrjkS3jPQDIE9zUAnILvoE0TX2I&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC2gS1d0tcMfCFdXLIoxn9eLz7numWIjks5s9XPkgaJpZM4PYIO8&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=86MtOWMYAEhZKDqpAVArVopzV2PLs6QRwZl5F620Ge0&s=hFWFoNMKyQ3RlmsE_uVIwk8qJYrATBkKn5vxgRJATXQ&e=>.
>

-- 
-- Upcoming iDigBio Events https://www.idigbio.org/calendar
-- Deborah Paul, iDigBio Digitization and Workforce Training Specialist
iDigBio -- Steering Committee Member, SPNHC Liaison and Member-At-Large, SYNTHESYS3 Representative
Institute for Digital Information, 234 LSB
Florida State University
Tallahassee, Florida 32306
850-644-6366

**Comment by ekrimmel** [comment]
looks good, Deb! I think PDFs are nice but I don't think necessary.

**Comment by debpaul** [comment]
Closing this - all issues dealt with.
