### ISSUE TITLE
GGBN request for Darwin Core Hour Webinar

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#28]
Hi All, Just got an email from Katie Barker at the Smithsonian on behalf of GGBN (with Mike Trizna and Gabriele Droege cc'd). They'd like to participate in dwchour. Stay tuned for details.

**Comment by debpaul** [comment]
Title, Abstract, Presenter Done and posted Title and Abstract to the tdwg/dwc-qa webinars page. Waiting on exact date (will be Feb or Mar 2018).

**Comment by debpaul** [comment]
Checklist to keep things moving for this webinar. To do items include:
- [x] Date and time = 21 February 2018 5 PM CET (11 AM EST, 1 PM Buenos Aires)
- [x] Title
- [x] Abstract
- [x] Presenter/s
- [x] Relevant links and reading materials
- [x] Moderator/s
- [x] iDigBio Calendar Announcement
- [x] add tdwg/dwc-qa/wiki/Webinars entry
- [x] Schedule sound/screen check
- [x] Request survey content from presenters
- [x] Send presenters feedback request to Shari and get survey link from Shari at iDigBio
- [x] Generate tinyURL for survey
- [x] Written [intro](https://github.com/VertNet/dwc-qa-manage/wiki/Webinar-Preparation-Checklist#example-webinar-introduction-script) to webinar
- [x] Prepare AdobeConnect environment
- [x] Send emails advertising DwC Hour one week prior
- [x] Send emails advertising DwC Hour one day prior
- [x] Render MP4
- [x] Update Webinar Wiki with recording links (Adobe Connect and MP4)
- [x] Close ticket when done

**Comment by debpaul** [comment]
Gabriel Dröge is offering several dates to choose from
21st February
22nd February
28th February
1st March
at: 11 am Washington (EST) / 5pm Berlin time.

I'm waiting now for feedback from Talia on Paleo+ Neontological Data webinar date preference.

**Comment by debpaul** [comment]
See that I've updated the checklist above. Calendar Announcement done see: https://www.idigbio.org/content/darwin-core-hour-making-dna-and-tissue-collections-available-using-ggbn-extensions-ipt

**Comment by debpaul** [comment]
FYI Specify will join this GGBN Webinar - to advertise that Specify now exports genetic/genomic data mapped to GGBN - for DwC-A packaging.

**Comment by debpaul** [comment]
last bits to be done - need to render the mp4 and update links to these recordings on the iDigBio Announcement and the DwC Hour Webinar Page

**Comment by ekrimmel** [comment]
i'll volunteer to render to this mp4 and update links

**Comment by debpaul** [comment]
Thanks!!! you are a good egg.

Deb


On 2018-03-13 4:29 PM, Erica Krimmel wrote:
>
> i'll volunteer to render to this mp4 and update links
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_VertNet_dwc-2Dqa-2Dmanage_issues_28-23issuecomment-2D372729177&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=pHuz0BGG3DZXFIiK2ogoLIMZ6w_0RdW83Hzxe7AjYfE&s=LV0pvQ4Qqdx0SrihQzt9jADX7lo8ZaqBQg1HVKO5-R4&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC2gSzu58T36IiBrkgwlVX93wOYtEC3Gks5td-5FPwgaJpZM4QGbV1&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=pHuz0BGG3DZXFIiK2ogoLIMZ6w_0RdW83Hzxe7AjYfE&s=p-GMv1eJTsNcV1bcLEsz5QZMAD3CnCBJfqfhYtPVFGw&e=>.
>

-- 
-- Upcoming iDigBio Events https://www.idigbio.org/calendar
-- Deborah Paul, iDigBio Digitization and Workforce Training Specialist
iDigBio -- Steering Committee Member
SPNHC Liaison, Member-At-Large and Member International Relations Committee
SYNTHESYS3 Representative
Institute for Digital Information, 234 LSB
Florida State University
Tallahassee, Florida 32306
850-644-6366

**Comment by ekrimmel** [comment]
recording [made](https://vimeo.com/245929146) and added to webinar wiki

**Comment by debpaul** [comment]
closing this ticket
