### ISSUE TITLE
Create Vimeo of TDWG 2017 Darwin Core Hour session

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-qa-manage#29]
AdobeConnect can be found at http://idigbio.adobeconnect.com/pnfbmfmo2uvh/

**Comment by ekrimmel** [comment]
I made the recording of both Deb's presentation and the mini DwC Hour--it's still only 30 minutes and I think nice to have both.

@kevinlove mp4 is [here](https://www.dropbox.com/s/1f31dtsccqhhd1e/DwC-at-TDWG-2017.mp4?dl=0), if you have a chance to add it to Vimeo. Thanks!

**Comment by kevinlove** [comment]
The mp4 has been uploaded to Vimeo, you can access it here:

https://vimeo.com/245787301

**Comment by debpaul** [comment]
Thank you @kevinlove!

**Comment by tucotuco** [comment]
Thanks very much, peops.

**Comment by debpaul** [comment]
Added this vimeo link to the webinars wiki.
