### ISSUE TITLE
Create Shared Presentations for TDWG 2017 Darwin Core Hour

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-qa-manage#30]
Entries have been made on the Webinars wiki page (https://github.com/tdwg/dwc-qa/wiki/Webinars) for the TDWG 2017 Standards in Action and bonus Darwin Core Extensions mini-hour. We need publicly shared Google Presentations for these and link to them in the wiki page both in the table at the top and in the Chapter entry below.

**Comment by pzermoglio** [comment]
Presentations uploaded to the Google Drive folder and linked in the wiki were appropriate.
Closing issue.
