### ISSUE TITLE
Prepare Darwin Core Hour #2 - Even Simple Is Hard

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-qa-manage#4]
First step, abstract to @debpaul.

**Comment by tucotuco** [comment]
Abstract submitted and published. Webinar "Even Simple is Hard" scheduled for 7 Mar 2017. Presentation preparation in progress.

**Comment by tucotuco** [comment]
Presented.

**Comment by garymotz** [comment]
This webinar had 127 unique attendees.
