### ISSUE TITLE
Prepare Darwin Core Hour #6 - Georeference Terms

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-qa-manage#8]
Seeking participation from Town Peterson and @dbloom. Tentatively scheduled as the fourth chapter in the Darwin Core Hour Series on the first Tuesday in May to cover accumulated questions about Georeference terms. Should cover the following issues

https://github.com/tdwg/dwc-qa/issues/23
https://github.com/tdwg/dwc-qa/issues/29
https://github.com/tdwg/dwc-qa/issues/30
https://github.com/tdwg/dwc-qa/issues/31
https://github.com/tdwg/dwc-qa/issues/32

Should not be scheduled until participation is confirmed and an abstract written.

**Comment by dbloom** [comment]
@tucotuco Can do.

**Comment by tucotuco** [comment]
Done.

**Comment by garymotz** [comment]
This webinar had 66 unique attendees.
